apiVersion: v1
kind: Secret
metadata:
  name: pgedge-creds
  namespace: crossplane-system
type: Opaque
stringData:
  endpoint: "{{ .Values.pgedge.appName }}-{{ .Values.cluster.name }}-data-rw.pgedge.svc"
  username: "admin"
  password: "" # Empty for cert auth
  database: "app"
  port: "5432"